### PR TITLE
min_len logic change

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi @Alexey-T 

The change to consider only minimal length with selections is finished.

Could you validate the changes please?

Thanks.

### CODE REVIEW

**Comment by Alexey-T** [comment]
i tried to validate it. too many changes. spaces changed. could you keep old spaces style, pls?

**Comment by Alexey-T** [comment]
could you keep old option names?

**Comment by JairoMartinezA** [comment]
Sure! Let me do the rollback.

**Comment by JairoMartinezA** [comment]
Ready!

**Comment by Alexey-T** [comment]
i reviewed the code. it seems okay. will apply it ASAP.

**Comment by Alexey-T** [comment]
in history.txt: path by .. -> patch by ..

**Comment by JairoMartinezA** [comment]
Ready!!! again.

**Comment by JairoMartinezA** [comment]
@Alexey-T 

I cannot see yet the changes when I re-download the plugin from the Addons Manager, I suppose you need to do something manually to update:

`https://sourceforge.net/projects/cudatext/files/addons/plugins/plugin.Highlight_Occurrences.zip/download`

**Comment by Alexey-T** [comment]
someone uploaded this plugin. insted of me. do you see it on SF.net?

**Comment by Alexey-T** [comment]
cudatext.sf.net.

**Comment by Alexey-T** [comment]
it was on SF.net day ago.

**Comment by JairoMartinezA** [comment]
Sorry @Alexey-T,

I don't know how is the plugin update process. I can see the last changes about *min_len* logic in the Git Repository, but when I try to download the plugin using the Addons Manager, the process is installing me a previous version. What I can see if that the addon-install process goes to SF repository, the problem is that SF have not the last git commit, how you can achieve this? Is a manual process?

**Comment by Alexey-T** [comment]
what should i do with Hilite Occurences plugin?

**Comment by Alexey-T** [comment]
i will upload the plugin again. somebody breaks the file on SF.

**Comment by JairoMartinezA** [comment]
Yes correct, you need to update SF hosted file.

**Comment by Alexey-T** [comment]
updated this file.

**Comment by JairoMartinezA** [comment]
It happens the same in this issue [ #2490](https://github.com/Alexey-T/CudaText/issues/2490)

**Comment by JairoMartinezA** [comment]
I just validated downloading again the plugin using the Addons Manager, all seems OK.

**Comment by Alexey-T** [comment]
thanks.

**Pull request merged**
