### PR TITLE
Option to move carets on occurrences.

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi @Alexey-T 

Could you help me to validate the next changes:
+ add: options to move carets around highlighted occurrences. Added some default keys.
+ add: option to force to select occurrences without minimum length required, False by default. Sometimes I need to select all text occurrences with less length that the default caret behavior.
+ fix: improvements on code. Avoid to call ed.action: EDACTION_FIND_ALL if the carets coincide with a previous highlighted word.

### CODE REVIEW

**Comment by Alexey-T** [comment]
>ed.set_caret(x0, y0, x0, y0)

need set_caret(x0, y0, -1, -1)

**Comment by Alexey-T** [comment]
global on_event_disabled
        on_event_disabled = True

maybe need to put this in the function beginning, it;'s in the middle.

**Comment by Alexey-T** [comment]
hotkey=...
i don't like this, pls no hotkeys, user can assign them. CudaExt plugin by @kvichans already has MANY hotkeys, i also don't like it but he is author

**Comment by Alexey-T** [comment]
"cmt": ["Maximal lenght for lines"],
typo

need "Maximal length of lines, which will be handled by plugin (plugin will skip longer lines)"

**Comment by Alexey-T** [comment]
"cmt": ["Selecting ocurrences do not apply minimum length"],
need "When plugin marks occurrences of selected text, it ignores 'minimal length' option"
or like it

**Comment by Alexey-T** [comment]
history
add: options to move carets around highlighted occurrences

need "4 plugin commands to move caret onto first/last/next/previous occurrence"

**Comment by JairoMartinezA** [comment]
I fixed suggested changes.

**Comment by CudaText-addons** [comment]
applied. can you pls, add your name like

    First Last (@nickname)

 to end of readme? near "Authors:". thanks.

**Comment by CudaText-addons** [comment]
and mark changes in history, with your name or nickname? like
```
- nnnnn.nn.nn (patch by @nnnnnnnn)
```

**Pull request merged**
